// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: third_party/xkratos/api/paginator/paginator.proto

package paginator

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginatorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PerPage     int64  `protobuf:"varint,1,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`             //每页多少条记录
	CurrentPage int64  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` //当前第几页
	Order       string `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`                                 //排序
}

func (x *PaginatorReq) Reset() {
	*x = PaginatorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReq) ProtoMessage() {}

func (x *PaginatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReq.ProtoReflect.Descriptor instead.
func (*PaginatorReq) Descriptor() ([]byte, []int) {
	return file_third_party_xkratos_api_paginator_paginator_proto_rawDescGZIP(), []int{0}
}

func (x *PaginatorReq) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PaginatorReq) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginatorReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type PaginatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemsCount int64 `protobuf:"varint,1,opt,name=items_count,json=itemsCount,proto3" json:"items_count,omitempty"` //总共多少条数据
	PagesCount int64 `protobuf:"varint,2,opt,name=pages_count,json=pagesCount,proto3" json:"pages_count,omitempty"` //总共多少页
}

func (x *PaginatorReply) Reset() {
	*x = PaginatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatorReply) ProtoMessage() {}

func (x *PaginatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatorReply.ProtoReflect.Descriptor instead.
func (*PaginatorReply) Descriptor() ([]byte, []int) {
	return file_third_party_xkratos_api_paginator_paginator_proto_rawDescGZIP(), []int{1}
}

func (x *PaginatorReply) GetItemsCount() int64 {
	if x != nil {
		return x.ItemsCount
	}
	return 0
}

func (x *PaginatorReply) GetPagesCount() int64 {
	if x != nil {
		return x.PagesCount
	}
	return 0
}

var File_third_party_xkratos_api_paginator_paginator_proto protoreflect.FileDescriptor

var file_third_party_xkratos_api_paginator_paginator_proto_rawDesc = []byte{
	0x0a, 0x31, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x78, 0x6b,
	0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x78, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18, 0x14, 0xd0, 0x01,
	0x01, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x44, 0x5a, 0x42,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6f, 0x6f, 0x6c, 0x69,
	0x73, 0x68, 0x6e, 0x6f, 0x6f, 0x62, 0x2f, 0x67, 0x6f, 0x2d, 0x78, 0x6b, 0x72, 0x61, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x3b, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_third_party_xkratos_api_paginator_paginator_proto_rawDescOnce sync.Once
	file_third_party_xkratos_api_paginator_paginator_proto_rawDescData = file_third_party_xkratos_api_paginator_paginator_proto_rawDesc
)

func file_third_party_xkratos_api_paginator_paginator_proto_rawDescGZIP() []byte {
	file_third_party_xkratos_api_paginator_paginator_proto_rawDescOnce.Do(func() {
		file_third_party_xkratos_api_paginator_paginator_proto_rawDescData = protoimpl.X.CompressGZIP(file_third_party_xkratos_api_paginator_paginator_proto_rawDescData)
	})
	return file_third_party_xkratos_api_paginator_paginator_proto_rawDescData
}

var file_third_party_xkratos_api_paginator_paginator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_third_party_xkratos_api_paginator_paginator_proto_goTypes = []interface{}{
	(*PaginatorReq)(nil),   // 0: xkratos.api.paginator.PaginatorReq
	(*PaginatorReply)(nil), // 1: xkratos.api.paginator.PaginatorReply
}
var file_third_party_xkratos_api_paginator_paginator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_third_party_xkratos_api_paginator_paginator_proto_init() }
func file_third_party_xkratos_api_paginator_paginator_proto_init() {
	if File_third_party_xkratos_api_paginator_paginator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_third_party_xkratos_api_paginator_paginator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_third_party_xkratos_api_paginator_paginator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_third_party_xkratos_api_paginator_paginator_proto_goTypes,
		DependencyIndexes: file_third_party_xkratos_api_paginator_paginator_proto_depIdxs,
		MessageInfos:      file_third_party_xkratos_api_paginator_paginator_proto_msgTypes,
	}.Build()
	File_third_party_xkratos_api_paginator_paginator_proto = out.File
	file_third_party_xkratos_api_paginator_paginator_proto_rawDesc = nil
	file_third_party_xkratos_api_paginator_paginator_proto_goTypes = nil
	file_third_party_xkratos_api_paginator_paginator_proto_depIdxs = nil
}
